describe('song function expression', function() {

  it('will print the right lyrics when passed the number one', function() {
    var expected = "1 green bottle hanging on the wall\n1 green bottle hanging on the wall\nAnd if that green bottle should accidentally fall down\nThere will be 0 green bottle hanging on the wall\n";
    expect(song(1)).toEqual(expected);
  });

  it('will print the right lyrics when passed the number two', function() {
    var expected = "2 green bottles hanging on the wall\n2 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 1 green bottle hanging on the wall\n" + "\n" + "1 green bottle hanging on the wall\n1 green bottle hanging on the wall\nAnd if that green bottle should accidentally fall down\nThere will be 0 green bottle hanging on the wall\n";
    expect(song(2)).toEqual(expected);
  });

  it('will print the right lyrics when passed any arbitrary number', function() {
    var expected = "3 green bottles hanging on the wall\n3 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 2 green bottles hanging on the wall\n" + "\n" + "2 green bottles hanging on the wall\n2 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 1 green bottle hanging on the wall\n" + "\n" + "1 green bottle hanging on the wall\n1 green bottle hanging on the wall\nAnd if that green bottle should accidentally fall down\nThere will be 0 green bottle hanging on the wall\n";
    expect(song(3)).toEqual(expected);
  });

  it('will print the entire nursery rhyme correctly', function() {
    var expected = "10 green bottles hanging on the wall\n10 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 9 green bottles hanging on the wall\n" + "\n" + "9 green bottles hanging on the wall\n9 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 8 green bottles hanging on the wall\n" + "\n" + "8 green bottles hanging on the wall\n8 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 7 green bottles hanging on the wall\n" + "\n" +  "7 green bottles hanging on the wall\n7 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 6 green bottles hanging on the wall\n" + "\n" + "6 green bottles hanging on the wall\n6 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 5 green bottles hanging on the wall\n" + "\n" +"5 green bottles hanging on the wall\n5 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 4 green bottles hanging on the wall\n" + "\n" + "4 green bottles hanging on the wall\n4 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 3 green bottles hanging on the wall\n" + "\n" + "3 green bottles hanging on the wall\n3 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 2 green bottles hanging on the wall\n" + "\n" + "2 green bottles hanging on the wall\n2 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 1 green bottle hanging on the wall\n" + "\n" + "1 green bottle hanging on the wall\n1 green bottle hanging on the wall\nAnd if that green bottle should accidentally fall down\nThere will be 0 green bottle hanging on the wall\n";
    // var expected = "10 green bottles hanging on the wall\n10 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 9 green bottles hanging on the wall\n" + "\n" + "9 green bottles hanging on the wall\n9 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 8 green bottles hanging on the wall\n" + "\n" + "8 green bottles hanging on the wall\n8 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 7 green bottles hanging on the wall\n" + "\n" + "7 green bottles hanging on the wall\n7 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 6 green bottles hanging on the wall\n" + "\n" + "6 green bottles hanging on the wall\n6 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 5 green bottles hanging on the wall\n" + "\n" + "5 green bottles hanging on the wall\n5 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 4 green bottles hanging on the wall\n" + "\n" + "4 green bottles hanging on the wall\n4 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 3 green bottles hanging on the wall\n" + "\n" + "3 green bottles hanging on the wall\n3 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 2 green bottles hanging on the wall\n" + "\n" + "2 green bottles hanging on the wall\n2 green bottles hanging on the wall\nAnd if one green bottle should accidentally fall down\nThere will be 1 green bottle hanging on the wall\n" + "\n" + "1 green bottle hanging on the wall\n1 green bottle hanging on the wall\nAnd if that one green bottle should accidentally fall down\nThere will be 0 green bottle hanging on the wall\n";
    expect(song(10)).toEqual(expected);
  });
});
